/*
 * @author: Sasikumar Bharanikumar
 * @version: 1.0
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ayst_stresstest_util_MemOpUtils */

#ifndef _Included_com_ayst_stresstest_util_MemOpUtils
#define _Included_com_ayst_stresstest_util_MemOpUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ayst_stresstest_util_MemOpUtils
 * Method:    memfill
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_discovery_thunderapp_MemOpUtils_malloc(JNIEnv *, jclass, jint size);

/*
 * Class:     com_ayst_stresstest_util_MemOpUtils
 * Method:    memfree
 * Signature: ()I
 */
JNIEXPORT void JNICALL Java_com_ayst_stresstest_util_MemOpUtils_free(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
